In [3]:
import numpy as np

In [4]:
from SALib.sample import saltelli

In [13]:
means = np.array([0.0, 0.0, 250.0, 400.0])
means = np.expand_dims(means, axis = 0).T

cov = np.array([
     [4,  2,  0,  0], 
     [2,  4,  0,  0], 
     [0,  0, 10, -2], 
     [0,  0, -2, 10]
])

composition = np.hstack((means, cov))
print(composition)


problem = {
    'num_vars': 4,
    'names': ['x1', 'x2', 'x3', 'x4'],
    'bounds': composition,
    'dists': 'multi_norm',
}

[[  0.   4.   2.   0.   0.]
 [  0.   2.   4.   0.   0.]
 [250.   0.   0.  10.  -2.]
 [400.   0.   0.  -2.  10.]]


In [14]:
X = saltelli.sample(problem, 1000, calc_second_order=False)

In [16]:
print(np.cov(X.T))

[[ 4.00150919e+00  1.99508552e+00 -2.42809871e-02  9.45874574e-03]
 [ 1.99508552e+00  3.99577636e+00 -2.28703954e-02 -2.11412989e-02]
 [-2.42809871e-02 -2.28703954e-02  9.99190795e+00 -1.95228945e+00]
 [ 9.45874574e-03 -2.11412989e-02 -1.95228945e+00  9.95717186e+00]]


In [17]:
print(np.mean(X, axis=0))

[3.08933655e-03 3.91430732e-03 2.49993216e+02 4.00008456e+02]
